### ISSUE TITLE
remove hard-code

### ISSUE THREAD

**Issue by rizzoa** [icshwi/e3-tools#10]
Hi
is it possible to remove the hard-code in the RELEASE file inside the configure directory ?
I.e. replace with

EPICS_BASE:=$(EPICS_BASE)
E3_REQUIRE_VERSION:=$(E3_REQUIRE_VERSION)
Thanks

**Comment by jeonghanlee** [comment]
We have the endless loop if we define them. I think you can override them by RELEASE.local file, which git doesn't track down.

**Comment by jeonghanlee** [comment]
TemplateGenerator only generates a file, users should add the proper version of each modules or applications which match their goals.  In addition, one can use *.local files in order to override that versions.  Now, I set EPICS_BASE=7.0.3 and REQUIRE=3.1.0. That is the baseline for e3 now.  I will close this issue. If you have more, please open another issues.

**Comment by rizzoa** [comment]
Hi,
that's fine, but since in any case before to create a template I have to load my EPICS env, with those two env variables the RELEASE file will have automatically the correct variables set, avoinding any mistake and the need to edit it if I have to work with another version of EPICS

**Comment by jeonghanlee** [comment]
Hmm, that is the interesting approach, but I need to understand how you work first clearly. I have few proposals in my mind, but it is better to discuss them more detail soon. So I re-open this issue until we agree with each other and we find the better way to handle your issue.

**Comment by rizzoa** [comment]
HI,
sure, you are welcome to come to my desk to discuss with me!

**Comment by jeonghanlee** [comment]
@rizzoa , I tried to add additional features in e3TemplateGenerator in order to meet your requests, the result is not the same as what I saw in your terminal.  I've got the following error if I have the same RELEASE file which you have.  Actually, that error is exactly what I expected as follows:

`RELEASE:2: *** Recursive variable 'EPICS_BASE' references itself (eventually).  Stop.`

Please check the release_test branch 248581fa2cccc8049d0bd8df772d36922ed705d2, you can generate the e3-something with new and test option (-r), it will create the same RELESE file which you describe.  And let me know what you get, if you find something wrong in the codes, you can freely to fix them as much as you want. Or simple let me know what you see and think also.

**Comment by rizzoa** [comment]
Hi Han,
you just miss a colon in the line. If you don't put it, the Makefile will not expand the env variable and then you get the error, you can fix by just doing this

EPICS_BASE := $(EPICS_BASE)

**Comment by jeonghanlee** [comment]
The branch was merged into master at fabeb5b. I confirmed your comment makes it works. Please spend your time to explain this feature to others in README.md soon. I close this issue.

**Comment by rizzoa** [comment]
HI @jeonghanlee please look at this 
https://github.com/rizzoa/e3-tools/commit/c38ba38b1508828545a3a5fb4b88e600aca2a5f6
I guess you have to fix it

**Comment by jeonghanlee** [comment]
@rizzoa , in order to get the RELEASE file with "Environmental variables", you need to add `-r` option. If not, it generates the hard-code RELEASE file instead of the dynamic one.  That function you changed is used to generate the fixed variables RELEASE file. 

I don't remove the hard-code RELEASE file, but add an additional option to create RELEASE file with "environment variables", which you would like to get.  Please run your commands such as 
`bash e3TemplateGenerator.bash -m your.conf -r`
will generate what you want to get.  Let me know what you can. 

In addition, I may add the another case scenario in travis in order to check a new feature which you would like to achieve.

**Comment by rizzoa** [comment]
Hi Han,
perferct, sorry for the missunderstanding, I am closing the issue!
Thanks
